## Admission webhooks make sure only requests with correctly formatted rules will get into the Operator.
## They also enable the sidecar injection for OpenTelemetryCollector and Instrumentation CR's
manager:
  collectorImage:
    repository: otel/opentelemetry-collector-k8s
admissionWebhooks:
  ## https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/README.md#tls-certificate-requirement
  ## TLS Certificate Option 1: Use certManager to generate self-signed certificate.
  ## certManager must be enabled. If enabled, always takes precedence over options 2 and 3.
  certManager:
    enabled: false
  ## TLS Certificate Option 2: Use Helm to automatically generate self-signed certificate.
  ## certManager must be disabled and autoGenerateCert must be enabled.
  ## If true and certManager.enabled is false, Helm will automatically create a self-signed cert and secret for you.
  autoGenerateCert:
    enabled: true
tolerations: 
  - key: "workload/critical"
    value: ""
    operator: "Equal"
    effect: "NoSchedule"
nodeSelector: 
  app/workload: critical